name: mypymolenv
channels:
  - schrodinger
  - salilab
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.79
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - curl=8.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - dssp=3.0.0
  - expat=2.5.0
  - fontconfig=2.14.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glew=2.1.0
  - glib=2.76.4
  - glib-tools=2.76.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.7.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=58.2
  - idna=3.4
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libglu=9.0.0
  - libgomp=13.1.0
  - libholoplaycore=0.1.0_rc4
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libpq=12.15
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.16
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.10.1
  - libzlib=1.2.13
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mtz2ccp4_px=1.1
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - numpy=1.21.6
  - openssl=3.1.2
  - packaging=23.1
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.2.1
  - ply=3.11
  - pmw=2.0.1+3
  - pthread-stubs=0.4
  - pymol=2.5.5
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - rigimol=1.3
  - setuptools=68.1.2
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.43.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.4
  - vtk-m=1.5.1
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
